volumes:
  static_root:

services:
  clogs: # Name of this container should not be changed
    image: clogs
    restart: unless-stopped
    build:
      context: .
      target: prod
      dockerfile: clogs/.docker/Dockerfile
    entrypoint: /clogs/clogs/.docker/entrypoint.sh
    command: "gunicorn clogs.core.wsgi -b :9000 --error-logfile gunicorn_log.log --workers=2 --threads=4 --worker-class=gthread"
    environment:
      DISABLE_MIGRATION_SCRIPT_ON_PRODUCTION:
      CLEAR_PUBLIC_SCHEMA_ON_FIXTURIZE:
      STATIC_URL:
      PREFIX_URL:
      PGDATABASE:
      PGUSER:
      PGPASSWORD:
      PGHOST:
      PGPORT:
      SECRET_KEY:
      EMAIL_HOST:
      EMAIL_PORT:
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
      EMAIL_USE_TLS:
      EMAIL_TO_CONSOLE:
      DEFAULT_FROM_EMAIL:
      PAGINATE_BY:
      ALLOWED_HOSTS:
      ALLOWED_CORS:
      ENABLE_2FA:
      SESSION_COOKIE_AGE:
      SESSION_SAVE_EVERY_REQUEST:
      SESSION_COOKIE_SAMESITE:
      SECURE_PROXY_SSL_HEADER:
      DEFAULT_SITE:
      LOCAL_TIME_ZONE_UTC:
      CSRF_TRUSTED_ORIGINS:
    ports:
      - "${DJANGO_DOCKER_PORT}:9000"
    networks:
      - default
